name: Build and Release

on:
  push:
    branches:
      - main
      - chore/yarn-to-pnpm
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - stable
          - alpha
        default: alpha

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump and Commit (Stable)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.release_type == 'stable'
        run: |
          npx standard-version
          git push --follow-tags

      - name: Bump and Commit (Alpha)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/chore/yarn-to-pnpm') || (github.event_name == 'workflow_dispatch' && inputs.release_type == 'alpha')
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD | sed 's/feature\///')
          branch=${branch//[^a-zA-Z0-9_-]/-}
          npx standard-version --prerelease "alpha-$branch" --skip.tag
          git push --follow-tags

  push:
    needs: create-new-release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      image_tag: ${{ steps.tag-stable.outputs.image_tag || steps.tag-alpha.outputs.image_tag }}
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from package.json
        id: version
        run: echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Generate image tag (Stable)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.release_type == 'stable'
        id: tag-stable
        run: echo "image_tag=${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Generate image tag (Alpha)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/chore/yarn-to-pnpm') || (github.event_name == 'workflow_dispatch' && inputs.release_type == 'alpha')
        id: tag-alpha
        run: echo "image_tag=${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build --cache-from democracy/democracy-server:latest -t democracy/democracy-server:${{ steps.tag-stable.outputs.image_tag || steps.tag-alpha.outputs.image_tag }} .

      - name: Push image to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub (Stable)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.release_type == 'stable'
        run: |
          docker tag democracy/democracy-server:${{ steps.tag-stable.outputs.image_tag || steps.tag-alpha.outputs.image_tag }} democracy/democracy-server:latest
          docker push democracy/democracy-server:latest
          docker push democracy/democracy-server:${{ steps.tag-stable.outputs.image_tag || steps.tag-alpha.outputs.image_tag }}

      - name: Push to Docker Hub (Alpha)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/chore/yarn-to-pnpm') || (github.event_name == 'workflow_dispatch' && inputs.release_type == 'alpha')
        run: docker push democracy/democracy-server:${{ steps.tag-stable.outputs.image_tag || steps.tag-alpha.outputs.image_tag }}

  create-pull-request-to-infrastructure:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: demokratie-live/infrastructure
          token: ${{ secrets.ACTION_INFRASTRUCTURE_PR }}
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create or update branch
        run: |
          BRANCH_NAME="democracy-server-${{ needs.push.outputs.image_tag }}"

          # Check if branch exists remotely
          if git ls-remote --heads origin $BRANCH_NAME | grep -q $BRANCH_NAME; then
            echo "Branch exists, checking out and updating"
            git fetch origin $BRANCH_NAME
            git checkout $BRANCH_NAME
            git pull origin $BRANCH_NAME
          else
            echo "Branch does not exist, creating new branch"
            git checkout -b $BRANCH_NAME
          fi

      - name: Edit file
        run: |
          sed -i -E "s/image: democracy\/democracy-server:.*$/image: democracy\/democracy-server:${{ needs.push.outputs.image_tag }}/g" kustomize/base/main/democracy-api-depl.yaml
          git add kustomize/base/main/democracy-api-depl.yaml
          git commit -m "chore(infrastructure): update Docker container version in Kubernetes YAML" || echo "No changes to commit"
          git push --set-upstream origin democracy-server-${{ needs.push.outputs.image_tag }}

      - name: Create Pull Request
        continue-on-error: true
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls
          owner: 'demokratie-live'
          repo: infrastructure
          title: 'New version for democracy-server ${{ needs.push.outputs.image_tag }}'
          base: main
          head: democracy-server-${{ needs.push.outputs.image_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_INFRASTRUCTURE_PR }}
