name: ğŸ§‘â€ğŸŒ¾ Integration-Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Test-on-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Testing on a k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3.0.2
      - run: |
          cat $HOME/.kube/config
      - name: ğŸŒ± Deploy preview env with Garden
        uses: garden-io/garden-action@v1.2
        with:
          command: test
          kubeconfig-location: $HOME/.kube/config
      - run: |
          cat $HOME/.kube/config
